package com.ikould.decorate.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ikould.decorate.entity.Authority;

@Repository
public interface AuthorityMapper {

	Authority findByMac(String mac);

	List<Authority> findAll();
	
	void update(Authority authority);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insert(Authority authority);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	Authority selectByPrimaryKey(Integer id);
}