package com.ikould.decorate.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ikould.decorate.entity.Material;

@Repository
public interface MaterialMapper {

	int deleteBySeriesId(int seriesId);

	int deleteByName(String name);

	List<Material> findAllBySeriesId(int seriesId);
	
	List<Material> findAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insert(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insertSelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	Material selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKeySelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKey(Material record);
}