package com.ikould.decorate.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ikould.decorate.entity.MaterialType;

@Repository
public interface MaterialTypeMapper {

	int deleteByName(String name);

	List<MaterialType> findAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insert(MaterialType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insertSelective(MaterialType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	MaterialType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKeySelective(MaterialType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtype
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKey(MaterialType record);
}