package com.ikould.decorate.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ikould.decorate.entity.MaterialText;

@Repository
public interface MaterialTextMapper {

	int deleteByMaterialId(int materialId);

	MaterialText findByMaterialId(int materialId);

	List<MaterialText> findAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insert(MaterialText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int insertSelective(MaterialText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	MaterialText selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKeySelective(MaterialText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table materialtext
	 *
	 * @mbggenerated Thu Jul 06 10:31:58 CST 2017
	 */
	int updateByPrimaryKey(MaterialText record);
}